/* Write your T-SQL query statement below */
WITH CTE AS(
    select
        ID,
        STUDENT,
        CEILING(ROW_NUMBER() OVER(ORDER BY ID) / 2.0) AS NUM
    FROM SEAT
),
CTE2 AS(
    SELECT 
        ID,
        LEAD(STUDENT) OVER(PARTITION BY NUM ORDER BY ID) AS NEXT_STUDENT,
        LAG(STUDENT) OVER(PARTITION BY NUM ORDER BY ID) AS PRE_STUDENT,
        STUDENT
    FROM CTE
)
SELECT
    ID,
    COALESCE(NEXT_STUDENT,PRE_STUDENT,STUDENT) AS STUDENT
FROM CTE2
